//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnTopReplica {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnTopReplica.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Created by: %. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AboutAuthor {
            get {
                return ResourceManager.GetString("AboutAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lorenz Cuno Klopfenstein に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AboutAuthorContent {
            get {
                return ResourceManager.GetString("AboutAuthorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Care to contribute to the project? You are welcome to improve available translations, start a new one for your native language or to check out the % from CodePlex. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AboutContribute {
            get {
                return ResourceManager.GetString("AboutContribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   source code に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AboutContributeContent {
            get {
                return ResourceManager.GetString("AboutContributeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OnTopReplica is based upon the WindowsFormsAero library and some other libraries and code sources. %. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AboutCreditsSources {
            get {
                return ResourceManager.GetString("AboutCreditsSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Read the full credits に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AboutCreditsSourcesContent {
            get {
                return ResourceManager.GetString("AboutCreditsSourcesContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Contribute に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AboutDividerContribute {
            get {
                return ResourceManager.GetString("AboutDividerContribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Credits に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AboutDividerCredits {
            get {
                return ResourceManager.GetString("AboutDividerCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   License に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AboutDividerLicense {
            get {
                return ResourceManager.GetString("AboutDividerLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The application is licensed under the % license, which meets the terms of the &quot;open-source&quot; definition specified by OSI. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AboutLicense {
            get {
                return ResourceManager.GetString("AboutLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Microsoft Reciprocal (MS-RL) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AboutLicenseContent {
            get {
                return ResourceManager.GetString("AboutLicenseContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A lightweight, real-time, always on top thumbnail of a window of your choice. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AboutSlogan {
            get {
                return ResourceManager.GetString("AboutSlogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About OnTopReplica に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Translators: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AboutTranslators {
            get {
                return ResourceManager.GetString("AboutTranslators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Christian Olaechea M., Daniel Zeus.EX, Federico Lorenzo, Goran Brecelj, Jan Romanczyk, Marco Kraxner, Patrik (batupata), Raúl Morillo, René Mihula, Roberto Leiro, Rodrigo Lourenço, Thomas Amundsen, Eric Hoffmann. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AboutTranslatorsContent {
            get {
                return ResourceManager.GetString("AboutTranslatorsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AboutVersion {
            get {
                return ResourceManager.GetString("AboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OnTopReplica に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Choose... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorAlert_ChooseColor {
            get {
                return ResourceManager.GetString("ColorAlert_ChooseColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Custom color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorAlert_CustomColor {
            get {
                return ResourceManager.GetString("ColorAlert_CustomColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Colors to detect: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorAlert_DetectColors {
            get {
                return ResourceManager.GetString("ColorAlert_DetectColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pause Color Alerts (all panels) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuPauseColorAlertAll {
            get {
                return ResourceManager.GetString("MenuPauseColorAlertAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Temporarily suspends color detection on every panel without changing settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuPauseColorAlertAllTT {
            get {
                return ResourceManager.GetString("MenuPauseColorAlertAllTT", resourceCulture);
            }
        }

        /// <summary>
        ///   Resume Color Alerts (all panels) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuResumeColorAlertAll {
            get {
                return ResourceManager.GetString("MenuResumeColorAlertAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Resumes color detection on every panel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuResumeColorAlertAllTT {
            get {
                return ResourceManager.GetString("MenuResumeColorAlertAllTT", resourceCulture);
            }
        }

        /// <summary>
        ///   Alarm when color disappears に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorAlert_AlertOnLoss {
            get {
                return ResourceManager.GetString("ColorAlert_AlertOnLoss", resourceCulture);
            }
        }

        /// <summary>
        ///   After the target color has been detected once, the alarm sounds when it is no longer found に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorAlert_AlertOnLossTooltip {
            get {
                return ResourceManager.GetString("ColorAlert_AlertOnLossTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Ignore dark frames に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorAlert_IgnoreDark {
            get {
                return ResourceManager.GetString("ColorAlert_IgnoreDark", resourceCulture);
            }
        }

        /// <summary>
        ///   Do not treat black screens or fade transitions as color loss に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorAlert_IgnoreDarkTooltip {
            get {
                return ResourceManager.GetString("ColorAlert_IgnoreDarkTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Consecutive misses: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorAlert_LossMissCount {
            get {
                return ResourceManager.GetString("ColorAlert_LossMissCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Number of consecutive samples without the target color before the loss alarm triggers に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorAlert_LossMissCountTooltip {
            get {
                return ResourceManager.GetString("ColorAlert_LossMissCountTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Detected: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorAlert_DetectedPixels {
            get {
                return ResourceManager.GetString("ColorAlert_DetectedPixels", resourceCulture);
            }
        }

        /// <summary>
        ///   Matching pixel counts from the most recent sample に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorAlert_DetectedPixelsTooltip {
            get {
                return ResourceManager.GetString("ColorAlert_DetectedPixelsTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Min pixels: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorAlert_MinPixels {
            get {
                return ResourceManager.GetString("ColorAlert_MinPixels", resourceCulture);
            }
        }

        /// <summary>
        ///   Minimum number of matching pixels required to trigger the alarm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorAlert_MinPixelsTooltip {
            get {
                return ResourceManager.GetString("ColorAlert_MinPixelsTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Enable Color Detection に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorAlert_Enable {
            get {
                return ResourceManager.GetString("ColorAlert_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gray に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorAlert_Gray {
            get {
                return ResourceManager.GetString("ColorAlert_Gray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sample Interval (ms): に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorAlert_Interval {
            get {
                return ResourceManager.GetString("ColorAlert_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (100-10000 range) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorAlert_IntervalRange {
            get {
                return ResourceManager.GetString("ColorAlert_IntervalRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time between color checks in milliseconds に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorAlert_IntervalTooltip {
            get {
                return ResourceManager.GetString("ColorAlert_IntervalTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (click and press a key) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorAlert_KeyNone {
            get {
                return ResourceManager.GetString("ColorAlert_KeyNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Press key on alarm: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorAlert_KeyPress {
            get {
                return ResourceManager.GetString("ColorAlert_KeyPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Color Alert... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorAlert_MenuTitle {
            get {
                return ResourceManager.GetString("ColorAlert_MenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Monitor window for specific color and alert に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorAlert_MenuTooltip {
            get {
                return ResourceManager.GetString("ColorAlert_MenuTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Orange に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorAlert_Orange {
            get {
                return ResourceManager.GetString("ColorAlert_Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Red に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorAlert_Red {
            get {
                return ResourceManager.GetString("ColorAlert_Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sample に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorAlert_SampleCursorColor {
            get {
                return ResourceManager.GetString("ColorAlert_SampleCursorColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click anywhere... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorAlert_SamplingInProgress {
            get {
                return ResourceManager.GetString("ColorAlert_SamplingInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sound file: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorAlert_SoundFile {
            get {
                return ResourceManager.GetString("ColorAlert_SoundFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Test alarm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorAlert_TestAlarm {
            get {
                return ResourceManager.GetString("ColorAlert_TestAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Color Alert に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorAlert_Title {
            get {
                return ResourceManager.GetString("ColorAlert_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alarm Volume: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorAlert_Volume {
            get {
                return ResourceManager.GetString("ColorAlert_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;Desktop Composition&apos; is not enabled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDwmOff {
            get {
                return ResourceManager.GetString("ErrorDwmOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You must enable desktop composition, by selecting &apos;Windows Aero&apos; as the theme used by Windows.
        ///
        ///To do so, right-click on the desktop and click on Personalize. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDwmOffContent {
            get {
                return ResourceManager.GetString("ErrorDwmOffContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error details に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorGenericInfoButton {
            get {
                return ResourceManager.GetString("ErrorGenericInfoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorGenericInfoText {
            get {
                return ResourceManager.GetString("ErrorGenericInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It appears that the selected window has been closed or is not valid anymore. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorGenericThumbnailHandleError {
            get {
                return ResourceManager.GetString("ErrorGenericThumbnailHandleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorGenericTitle {
            get {
                return ResourceManager.GetString("ErrorGenericTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Desktop Composition&apos; is not supported on your Operating System.
        ///You must run this application on Windows Vista Home Premium or better. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorNoDwm {
            get {
                return ResourceManager.GetString("ErrorNoDwm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Desktop Composition unsupported に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorNoDwmTitle {
            get {
                return ResourceManager.GetString("ErrorNoDwmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No thumbnail loaded. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorNoThumbnail {
            get {
                return ResourceManager.GetString("ErrorNoThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to create thumbnail に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorUnableToCreateThumbnail {
            get {
                return ResourceManager.GetString("ErrorUnableToCreateThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable Click-Through mode? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InfoClickThrough {
            get {
                return ResourceManager.GetString("InfoClickThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In this mode the fullscreen window will behave as a partially transparent overlay, allowing you to click on the other windows behind it.
        ///
        ///To return to normal mode, use the disable command in the menu of the OnTopReplica tray icon. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InfoClickThroughContent {
            get {
                return ResourceManager.GetString("InfoClickThroughContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click-Through mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InfoClickThroughTitle {
            get {
                return ResourceManager.GetString("InfoClickThroughTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hides the main window and displays the &quot;about&quot; box. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuAboutTT {
            get {
                return ResourceManager.GetString("MenuAboutTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add panel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuAddPanel {
            get {
                return ResourceManager.GetString("MenuAddPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Opens another panel window to monitor a different region に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuAddPanelTT {
            get {
                return ResourceManager.GetString("MenuAddPanelTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Advanced に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuAdvanced {
            get {
                return ResourceManager.GetString("MenuAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show window border に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuChrome {
            get {
                return ResourceManager.GetString("MenuChrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggles the display of the window border. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuChromeTT {
            get {
                return ResourceManager.GetString("MenuChromeTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable Click-Through に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuClickThrough {
            get {
                return ResourceManager.GetString("MenuClickThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OnTopReplica will behave like a transparent overlay that lets your clicks through to the windows below. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuClickThroughTT {
            get {
                return ResourceManager.GetString("MenuClickThroughTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuClose {
            get {
                return ResourceManager.GetString("MenuClose", resourceCulture);
            }
        }

        /// <summary>
        ///   Close panel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuClosePanel {
            get {
                return ResourceManager.GetString("MenuClosePanel", resourceCulture);
            }
        }

        /// <summary>
        ///   Disable Click-Through (all panels) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuDisableClickThroughAll {
            get {
                return ResourceManager.GetString("MenuDisableClickThroughAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disable click-through mode for all panels in this set. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuDisableClickThroughAllTT {
            get {
                return ResourceManager.GetString("MenuDisableClickThroughAllTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable Click-Through (all panels) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuEnableClickThroughAll {
            get {
                return ResourceManager.GetString("MenuEnableClickThroughAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable click-through mode for all panels in this set. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuEnableClickThroughAllTT {
            get {
                return ResourceManager.GetString("MenuEnableClickThroughAllTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Closes all panels and exits the program に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuExitTT {
            get {
                return ResourceManager.GetString("MenuExitTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Opacity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuOpacity {
            get {
                return ResourceManager.GetString("MenuOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuOpen {
            get {
                return ResourceManager.GetString("MenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Displays OnTopReplica. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuOpenTT {
            get {
                return ResourceManager.GetString("MenuOpenTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minimize に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuReduce {
            get {
                return ResourceManager.GetString("MenuReduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minimizes OnTopReplica to the task bar (or the tray). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuReduceTT {
            get {
                return ResourceManager.GetString("MenuReduceTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select region... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuRegion {
            get {
                return ResourceManager.GetString("MenuRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Switches to &quot;region mode&quot;, that allows you to select a limited region of the source&apos;s window as thumbnail. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuRegionTT {
            get {
                return ResourceManager.GetString("MenuRegionTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Displays the settings panel. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuSettingsTT {
            get {
                return ResourceManager.GetString("MenuSettingsTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Switch to window に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuSwitch {
            get {
                return ResourceManager.GetString("MenuSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Switches to the source window and hides OnTopReplica. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuSwitchTT {
            get {
                return ResourceManager.GetString("MenuSwitchTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select window に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuWindows {
            get {
                return ResourceManager.GetString("MenuWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - none - に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuWindowsNone {
            get {
                return ResourceManager.GetString("MenuWindowsNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Displays a list of window you can select as thumbnail source. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuWindowsTT {
            get {
                return ResourceManager.GetString("MenuWindowsTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - whole - に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuWindowsWholeRegion {
            get {
                return ResourceManager.GetString("MenuWindowsWholeRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bottom に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RegionsBottom {
            get {
                return ResourceManager.GetString("RegionsBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current region: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RegionsCurrentRegion {
            get {
                return ResourceManager.GetString("RegionsCurrentRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RegionsDeleteButton {
            get {
                return ResourceManager.GetString("RegionsDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Done に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RegionsDoneButton {
            get {
                return ResourceManager.GetString("RegionsDoneButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Height に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RegionsHeight {
            get {
                return ResourceManager.GetString("RegionsHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RegionsLeft {
            get {
                return ResourceManager.GetString("RegionsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RegionsResetButton {
            get {
                return ResourceManager.GetString("RegionsResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RegionsRight {
            get {
                return ResourceManager.GetString("RegionsRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RegionsSaveButton {
            get {
                return ResourceManager.GetString("RegionsSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stored regions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RegionsStoredRegions {
            get {
                return ResourceManager.GetString("RegionsStoredRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Regions: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RegionsTitle {
            get {
                return ResourceManager.GetString("RegionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Top に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RegionsTop {
            get {
                return ResourceManager.GetString("RegionsTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Width に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RegionsWidth {
            get {
                return ResourceManager.GetString("RegionsWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   X に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RegionsX {
            get {
                return ResourceManager.GetString("RegionsX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Y に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RegionsY {
            get {
                return ResourceManager.GetString("RegionsY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right-click here to start... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RightClick {
            get {
                return ResourceManager.GetString("RightClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto hide: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsAutoHideTitle {
            get {
                return ResourceManager.GetString("SettingsAutoHideTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Hide panels when the cloned window is inactive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsAutoHideWhenSourceInactive {
            get {
                return ResourceManager.GetString("SettingsAutoHideWhenSourceInactive", resourceCulture);
            }
        }

        /// <summary>
        ///   Pause color alerts when the window is lost に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsPauseColorAlertWhenSourceLost {
            get {
                return ResourceManager.GetString("SettingsPauseColorAlertWhenSourceLost", resourceCulture);
            }
        }


        /// <summary>
        ///   Color alert indicator: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsIndicatorTitle {
            get {
                return ResourceManager.GetString("SettingsIndicatorTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Show indicator dot に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsIndicatorShow {
            get {
                return ResourceManager.GetString("SettingsIndicatorShow", resourceCulture);
            }
        }

        /// <summary>
        ///   Dot size (px): に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsIndicatorSize {
            get {
                return ResourceManager.GetString("SettingsIndicatorSize", resourceCulture);
            }
        }

        /// <summary>
        ///   Running color: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsIndicatorRunColor {
            get {
                return ResourceManager.GetString("SettingsIndicatorRunColor", resourceCulture);
            }
        }

        /// <summary>
        ///   Paused color: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsIndicatorPauseColor {
            get {
                return ResourceManager.GetString("SettingsIndicatorPauseColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsLanguageTitle {
            get {
                return ResourceManager.GetString("SettingsLanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Requires a restart. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsRestartRequired {
            get {
                return ResourceManager.GetString("SettingsRestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
    }
}
